import { Hono } from 'hono';
import { bearerAuth } from 'hono/bearer-auth';

type Bindings = {
  DB: D1Database;
  API_TOKEN: string;
  GITHUB_TOKEN: string;
  GITHUB_REPO: string;
};

const app = new Hono<{ Bindings: Bindings }>();

// Auth middleware
app.use('/api/*', async (c, next) => {
  const auth = bearerAuth({ token: c.env.API_TOKEN });
  return auth(c, next);
});

// POST /api/log — バッチログ受信
app.post('/api/log', async (c) => {
  const { entries } = await c.req.json<{
    entries: Array<{
      timestamp: string;
      type: 'location' | 'sleep' | 'memo';
      latitude?: number;
      longitude?: number;
      place_name?: string;
      payload?: string;
    }>;
  }>();

  if (!entries?.length) return c.json({ error: 'No entries' }, 400);

  const stmt = c.env.DB.prepare(
    'INSERT INTO logs (timestamp, type, latitude, longitude, place_name, payload) VALUES (?, ?, ?, ?, ?, ?)'
  );

  const batch = entries.map((e) =>
    stmt.bind(e.timestamp, e.type, e.latitude ?? null, e.longitude ?? null, e.place_name ?? null, e.payload ?? null)
  );

  await c.env.DB.batch(batch);
  return c.json({ ok: true, count: entries.length });
});

// GET /api/logs?date=YYYY-MM-DD
app.get('/api/logs', async (c) => {
  const date = c.req.query('date') ?? new Date().toISOString().slice(0, 10);
  const results = await c.env.DB.prepare(
    "SELECT * FROM logs WHERE date(timestamp) = ? ORDER BY timestamp ASC"
  ).bind(date).all();
  return c.json(results);
});

// GET /api/summary?date=YYYY-MM-DD — 日報プレビュー
app.get('/api/summary', async (c) => {
  const date = c.req.query('date') ?? new Date().toISOString().slice(0, 10);
  const markdown = await generateDailyReport(c.env.DB, date);
  return c.text(markdown);
});

// Cron handler — GitHub Issue 日報生成
export default {
  fetch: app.fetch,
  async scheduled(event: ScheduledEvent, env: Bindings) {
    // 23:50 JST = 14:50 UTC → 今日の日報
    const now = new Date();
    const jstDate = new Date(now.getTime() + 9 * 60 * 60 * 1000);
    const date = jstDate.toISOString().slice(0, 10);

    const markdown = await generateDailyReport(env.DB, date);
    if (!markdown) return;

    const dayOfWeek = ['日', '月', '火', '水', '木', '金', '土'][jstDate.getDay()];
    const title = `📍 nehan日報 ${date}（${dayOfWeek}）`;

    await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}/issues`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
        'User-Agent': 'nehan-ai-worker',
      },
      body: JSON.stringify({
        title,
        body: markdown,
        labels: ['nehan', 'daily-report'],
      }),
    });
  },
};

async function generateDailyReport(db: D1Database, date: string): Promise<string> {
  const { results } = await db.prepare(
    "SELECT * FROM logs WHERE date(timestamp) = ? ORDER BY timestamp ASC"
  ).bind(date).all();

  if (!results?.length) return '';

  const locations = results.filter((r: any) => r.type === 'location');
  const sleeps = results.filter((r: any) => r.type === 'sleep');
  const memos = results.filter((r: any) => r.type === 'memo');

  let md = `# 📍 nehan日報 ${date}\n\n`;

  // 睡眠
  if (sleeps.length > 0) {
    md += `## 🛏️ 睡眠\n`;
    for (const s of sleeps) {
      try {
        const p = JSON.parse((s as any).payload || '{}');
        md += `- 就寝: ${p.asleep?.slice(11, 16) ?? '?'} → 起床: ${p.awake?.slice(11, 16) ?? '?'}\n`;
        if (p.stages) {
          for (const st of p.stages) {
            md += `  - ${st.stage}: ${st.minutes}min\n`;
          }
        }
      } catch {
        md += `- (データ解析エラー)\n`;
      }
    }
    md += '\n';
  }

  // 訪問場所
  if (locations.length > 0) {
    md += `## 📍 訪問場所\n`;
    md += `| 時刻 | 場所 | 座標 |\n|------|------|------|\n`;
    for (const l of locations) {
      const time = (l as any).timestamp?.slice(11, 16) ?? '?';
      const place = (l as any).place_name || `${(l as any).latitude?.toFixed(4)}, ${(l as any).longitude?.toFixed(4)}`;
      const coord = `${(l as any).latitude?.toFixed(4)}, ${(l as any).longitude?.toFixed(4)}`;
      md += `| ${time} | ${place} | ${coord} |\n`;
    }
    md += '\n';
  }

  // メモ
  if (memos.length > 0) {
    md += `## 📝 メモ\n`;
    for (const m of memos) {
      const time = (m as any).timestamp?.slice(11, 16) ?? '?';
      md += `- ${time} ${(m as any).payload || ''}\n`;
    }
    md += '\n';
  }

  md += `---\n*Generated by nehan.ai*\n`;
  return md;
}
