import { Hono } from 'hono';
import { bearerAuth } from 'hono/bearer-auth';

type Bindings = {
  DB: D1Database;
  API_TOKEN: string;
};

const app = new Hono<{ Bindings: Bindings }>();

// Auth middleware
app.use('/api/*', async (c, next) => {
  const auth = bearerAuth({ token: c.env.API_TOKEN });
  return auth(c, next);
});

// POST /api/log — バッチログ受信
app.post('/api/log', async (c) => {
  const { entries } = await c.req.json<{
    entries: Array<{
      timestamp: string;
      type: 'location' | 'sleep' | 'memo';
      latitude?: number;
      longitude?: number;
      place_name?: string;
      payload?: string;
    }>;
  }>();

  if (!entries?.length) return c.json({ error: 'No entries' }, 400);

  const stmt = c.env.DB.prepare(
    'INSERT INTO logs (timestamp, type, latitude, longitude, place_name, payload) VALUES (?, ?, ?, ?, ?, ?)'
  );

  const batch = entries.map((e) =>
    stmt.bind(e.timestamp, e.type, e.latitude ?? null, e.longitude ?? null, e.place_name ?? null, e.payload ?? null)
  );

  await c.env.DB.batch(batch);
  return c.json({ ok: true, count: entries.length });
});

// GET /api/logs?date=YYYY-MM-DD
app.get('/api/logs', async (c) => {
  const date = c.req.query('date') ?? new Date().toISOString().slice(0, 10);
  const results = await c.env.DB.prepare(
    "SELECT * FROM logs WHERE date(timestamp, '+9 hours') = ? ORDER BY timestamp ASC"
  ).bind(date).all();
  return c.json(results);
});

// GET /api/summary?date=YYYY-MM-DD — 日報プレビュー
app.get('/api/summary', async (c) => {
  const date = c.req.query('date') ?? new Date().toISOString().slice(0, 10);
  const markdown = await generateDailyReport(c.env.DB, date);
  return c.text(markdown);
});

export default app;

function toJST(ts: string): string {
  try {
    const d = new Date(ts);
    return d.toLocaleTimeString('ja-JP', { timeZone: 'Asia/Tokyo', hour: '2-digit', minute: '2-digit', hour12: false });
  } catch {
    return ts?.slice(11, 16) ?? '?';
  }
}

async function generateDailyReport(db: D1Database, date: string): Promise<string> {
  const { results } = await db.prepare(
    "SELECT * FROM logs WHERE date(timestamp, '+9 hours') = ? ORDER BY timestamp ASC"
  ).bind(date).all();

  if (!results?.length) return '';

  const locations = results.filter((r: any) => r.type === 'location');
  const sleeps = results.filter((r: any) => r.type === 'sleep');
  const memos = results.filter((r: any) => r.type === 'memo');

  let md = `# 📍 nehan日報 ${date}\n\n`;

  // 睡眠
  if (sleeps.length > 0) {
    md += `## 🛏️ 睡眠\n`;
    for (const s of sleeps) {
      try {
        const p = JSON.parse((s as any).payload || '{}');
        md += `- 就寝: ${p.asleep?.slice(11, 16) ?? '?'} → 起床: ${p.awake?.slice(11, 16) ?? '?'}\n`;
        if (p.stages) {
          for (const st of p.stages) {
            md += `  - ${st.stage}: ${st.minutes}min\n`;
          }
        }
      } catch {
        md += `- (データ解析エラー)\n`;
      }
    }
    md += '\n';
  }

  // 訪問場所
  if (locations.length > 0) {
    md += `## 📍 訪問場所\n`;
    md += `| 時刻 | 場所 | 座標 |\n|------|------|------|\n`;
    for (const l of locations) {
      const time = toJST((l as any).timestamp);
      const place = (l as any).place_name || `${(l as any).latitude?.toFixed(4)}, ${(l as any).longitude?.toFixed(4)}`;
      const coord = `${(l as any).latitude?.toFixed(4)}, ${(l as any).longitude?.toFixed(4)}`;
      md += `| ${time} | ${place} | ${coord} |\n`;
    }
    md += '\n';
  }

  // メモ
  if (memos.length > 0) {
    md += `## 📝 メモ\n`;
    for (const m of memos) {
      const time = toJST((m as any).timestamp);
      md += `- ${time} ${(m as any).payload || ''}\n`;
    }
    md += '\n';
  }

  md += `---\n*Generated by nehan.ai*\n`;
  return md;
}
