name = "nehan-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "nehan-db"
database_id = "5b746e48-0a3b-41f4-8e93-8f1c1cb1bdc8"

# secrets (set via wrangler secret put):
# API_TOKEN
